base.accept('escape', sys.exit)
        base.accept('w', self.set_movement, ["left", 1])
        base.accept('w-up', self.set_movement, ["left", 0])
        base.accept('s', self.set_movement, ["right", 1])
        base.accept('s-up', self.set_movement, ["right", 0])
        base.accept('a', self.set_movement, ["backward", 1])
        base.accept('a-up', self.set_movement, ["backward", 0])
        base.accept('d', self.set_movement, ["forward", 1])
        base.accept('d-up', self.set_movement, ["forward", 0])
        base.accept('space', self.set_movement, ["up", 1])
        base.accept('space-up', self.set_movement, ["up", 0])
        base.accept('shift', self.set_movement, ["down", 1])
        base.accept('shift-up', self.set_movement, ["down", 0])